nodeLinker: pnp

packageExtensions:
  echarts-for-react@*:
    dependencies:
      tslib: "*"
  rc-cascader@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-checkbox@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-collapse@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-dialog@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-dropdown@*:
    dependencies:
      rc-util: "*"
  rc-input-number@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-menu@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-progress@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-rate@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-tabs@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-tooltip@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-trigger@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-upload@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-util@*:
    dependencies:
      react: "*"
      react-dom: "*"
  react-dom@*:
    dependencies:
      react: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpEnableEsmLoader: true

pnpMode: strict

supportedArchitectures:
  cpu:
    - current
    - x86
    - arm64
  os:
    - current
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-3.2.1.cjs
